language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
  - yarn
before_install:
- openssl aes-256-cbc -K $encrypted_aaf2e10e3657_key -iv $encrypted_aaf2e10e3657_iv
  -in deploy_key.enc -out ./deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host $IP\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master